jwt:
  secret: "iYCjUdNssmFaDDcrGw6+SehQ0X3tiKZtjG1MFNb/HVo/ewndia3mNTbxS1Qxrgkq1Ggmzc1cYUUPmClCA5gj2A=="
  expiration-ms: 86400000

spring:
  application:
    name: FitnessClub

  datasource:
    url: jdbc:postgresql://localhost:8652/fitnessclub
    username: comp3005
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: false
springdoc:
  api-docs:
    enabled: true
    path: /openapi.json